VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClinicDef"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public FacilityNCID As String
Public NCID As String
Public Name As String
Public IEN As String
Public MEPRSCode As String
Public MeprsDescription As String
Public MeprsIEN As String
Public LocationType As String
Public WalkInAllowed As Boolean
Public SickCallAllowed As Boolean
Public StreetAddress As String
Public BuildingNumber As String
Public City As String
Public State As String
Public ZipCode As String
Public DmisIdCode As String

