VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IDENTAL_DRC"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get PatLvlDRC() As Integer

End Property

Public Property Get PatLvlLstExmDate() As Date

End Property

Public Property Get PatLvlLstChgDate() As Date

End Property

Public Property Get EncLvlDRC() As Integer

End Property

Public Property Get EncLvlLstExmDte() As Date

End Property

Public Property Get EncLvlLstChgDte() As Date

End Property

Public Sub UpdateDRC()

End Sub

